"""support tickets

Revision ID: 06108259096c
Revises: 9802f18c14af
Create Date: 2021-06-18 15:07:31.895128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06108259096c'
down_revision = '9802f18c14af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supporttickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticketname', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('sendername', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('response', sa.String(length=1000), nullable=True),
    sa.Column('progress', sa.String(length=50), nullable=True),
    sa.Column('assignedto', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supporttickets')
    # ### end Alembic commands ###
