"""support tickets2

Revision ID: e0ae844dfe41
Revises: 06108259096c
Create Date: 2021-06-18 15:15:40.986231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ae844dfe41'
down_revision = '06108259096c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supporttickets2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticketname', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('sendername', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('response', sa.String(length=1000), nullable=True),
    sa.Column('progress', sa.String(length=50), nullable=True),
    sa.Column('assignedto', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('supporttickets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supporttickets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticketname', sa.VARCHAR(length=100), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('message', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('sendername', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=11), nullable=True),
    sa.Column('response', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('progress', sa.VARCHAR(length=50), nullable=True),
    sa.Column('assignedto', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('supporttickets2')
    # ### end Alembic commands ###
