"""empty message

Revision ID: f93a58ed3b7d
Revises: dbbf62da1adc
Create Date: 2021-06-22 16:02:23.840009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93a58ed3b7d'
down_revision = 'dbbf62da1adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('studentfirstname', sa.String(length=50), nullable=True),
    sa.Column('studentsurname', sa.String(length=50), nullable=True),
    sa.Column('projectname', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('coursename', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('feedback', sa.String(length=1000), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    # ### end Alembic commands ###
